name: 'Lint'
description: 'Run commit hooks'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Restore cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: py3.7-${{ runner.os }}-venv-cache-${{ hashFiles('**/poetry.lock') }}
    - name: Install poetry
      run: |
        pip install poetry==1.1.5
        poetry config virtualenvs.in-project true
    - name: Install dependencies
      run: |
        poetry install -E http -E sql --no-root
        poetry run task compile
        poetry install
    - name: Lint
      run: poetry run task lint
